import Head from 'next/head';
import ProjectCards from '../components/ProjectCards/ProjectCards';
import {
  Container,
  Main,
  Title,
  Description,
  WebLink,
} from '../styles/sharedstyles';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet" />
      </Head>

      <Main>
        <Title>50 Projects</Title>

        <Description>
          NextJS and Styled Components implementation of Udemy course
        </Description>
        <Description>
          <WebLink
            href="https://www.udemy.com/course/50-projects-50-days/"
            target="_blank"
          >
            50 Projects In 50 Days - HTML, CSS & JavaScript
          </WebLink>
        </Description>

        <ProjectCards />
      </Main>
    </Container>
  );
}
